package user_service.enums;

public enum Department {
    COMPUTER_ENGINEERING,
    SOFTWARE_ENGINEERING,
    ELECTRICAL_ELECTRONICS_ENGINEERING,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    MATHEMATICS,
    PHYSICS,
    CHEMISTRY,
    BIOLOGY,
    BUSINESS_ADMINISTRATION,
    ECONOMICS,
    PSYCHOLOGY,
    TURKISH_LANGUAGE_AND_LITERATURE,
    ENGLISH_LANGUAGE_AND_LITERATURE,
    OTHER
}
