package notification_service.enums;

public enum NotificationType {
    POST_LIKED,
    POST_COMMENTED,
    COMMENT_REPLIED,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    EVENT_CREATED,
    EVENT_REMINDER,
    EVENT_CANCELLED,
    CHAT_MESSAGE_RECEIVED,
    CHAT_GROUP_INVITE,
    CHAT_MENTION,
    SECURITY_ALERT,
    PROFILE_UPDATED,
    SYSTEM_ANNOUNCEMENT
}
