server.port=8080
spring.application.name=api-gateway

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=api-gateway
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET}
internal.service.token=${INTERNAL_SERVICE_TOKEN}

gateway.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:8080

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
management.endpoint.gateway.enabled=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/v1/api/users/**

spring.cloud.gateway.routes[2].id=post-service
spring.cloud.gateway.routes[2].uri=lb://post-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/v1/api/posts/**

spring.cloud.gateway.routes[3].id=friend-service
spring.cloud.gateway.routes[3].uri=lb://friend-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/v1/api/friends/**

spring.cloud.gateway.routes[4].id=media-service
spring.cloud.gateway.routes[4].uri=lb://media-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/v1/api/media/**

spring.cloud.gateway.routes[5].id=event-service
spring.cloud.gateway.routes[5].uri=lb://event-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/v1/api/events/**

spring.cloud.gateway.routes[6].id=logging-service
spring.cloud.gateway.routes[6].uri=lb://logging-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/v1/api/logs/**

spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://notification-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/v1/api/notifications/**

spring.cloud.gateway.routes[8].id=chat-service
spring.cloud.gateway.routes[8].uri=lb://chat-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/v1/api/chats/**

spring.cloud.gateway.routes[9].id=chat-service-websocket
spring.cloud.gateway.routes[9].uri=lb:ws://chat-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/socket.io/**