server.port=8091
spring.application.name=notification-service

spring.datasource.url=jdbc:postgresql://localhost:5432/campusconnect_notification
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=notification-service
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}
spring.cloud.consul.discovery.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

notification.scheduler.enabled=true
notification.retry.max-attempts=3
notification.expire.cleanup-days=30

user.service.name=user-service
logging.service.name=logging-service

# ==========================================
# Mail (SMTP)
# ==========================================
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9aa54e001@smtp-brevo.com
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# OpenAPI / Scalar
# ==========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false
scalar.enabled=true
scalar.path=/scalar
scalar.title=Campus Connect Notification Service API
