# =============================================
# APPLICATION CONFIG
# =============================================
spring.application.name=auth-service
server.port=8081

# =============================================
# CONSUL SERVICE DISCOVERY
# =============================================
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=auth-service
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}
spring.cloud.consul.discovery.prefer-ip-address=true

# =============================================
# DATABASE - PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/campusconnect_auth
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / HIBERNATE
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# ACTUATOR
# =============================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =============================================
# SPRINGDOC / SWAGGER
# =============================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# =============================================
# JWT CONFIGURATION
# =============================================
jwt.secret=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000